name: crisis360app
description: "An app to help people who affected by the disasters."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  http: ^1.6.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  delightful_toast: ^1.1.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo/logo2.png

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
    - assets/images/welcome_image_1.jpg
    - assets/images/welcome_image_2.jpg
    - assets/images/login_page_image.png
    - assets/images/register_page_image.jpg

  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
         - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700